Object.defineProperty(exports, "__esModule", { value: true });
var Categories;
(function (Categories) {
    Categories[Categories["Controller"] = 0] = "Controller";
    Categories[Categories["DimmableControl"] = 1] = "DimmableControl";
    Categories[Categories["RelayControl"] = 2] = "RelayControl";
    Categories[Categories["NetworkBridge"] = 3] = "NetworkBridge";
    Categories[Categories["IrrigationControl"] = 4] = "IrrigationControl";
    Categories[Categories["ClimateControl"] = 5] = "ClimateControl";
    Categories[Categories["PoolControl"] = 6] = "PoolControl";
    Categories[Categories["SensorActuator"] = 7] = "SensorActuator";
    Categories[Categories["HomeEntertainment"] = 8] = "HomeEntertainment";
    Categories[Categories["EnergyManagement"] = 9] = "EnergyManagement";
    Categories[Categories["ApplianceControl"] = 10] = "ApplianceControl";
    Categories[Categories["WindowShadeControl"] = 14] = "WindowShadeControl";
    Categories[Categories["AccessControl"] = 15] = "AccessControl";
    Categories[Categories["SecurityHealthSafety"] = 16] = "SecurityHealthSafety";
    Categories[Categories["A10X10"] = 113] = "A10X10";
    Categories[Categories["Virtual"] = 127] = "Virtual";
    Categories[Categories["Unknown"] = 254] = "Unknown";
})(Categories = exports.Categories || (exports.Categories = {}));
