import { ISYDevice } from './isy';
export declare class DeviceFactory {
    static LINK_MANAGEMENT_NAME: string;
    static LIGHT_NAME: string;
    static LIGHT_ADDRESS: string;
    static DEVICE_TYPE: string;
    static ON_LEVEL: string;
    static OFF_LEVEL: string;
    static RAMP_RATE: string;
    static STATUS: string;
    static LIGHT_ON: string;
    static LIGHT_OFF: string;
    static LIGHT_FAST_ON: string;
    static LIGHT_FAST_OFF: string;
    static LIGHT_DIM: string;
    static LIGHT_BRIGHTEN: string;
    static LIGHT_MOVE_UP: string;
    static LIGHT_MOVE_DOWN: string;
    static SETPOINT: string;
    static HUMIDITY: string;
    static TEMPERATURE: string;
    static LOCK_DOOR: string;
    static UNLOCK_DOOR: string;
    static LOCKED_DOOR: string;
    static UNLOCKED_DOOR: string;
    static ACCUMULATED_POWER: string;
    static RESET: string;
    static ADVANCED: string;
    static LED_BRIGHTNESS: string;
    static LOCKED_DOOR_ST: string;
    static UNLOCKED_DOOR_ST: string;
    static SCENE_UNSUPPORTED_VALUE: string;
    static SCENE_NO_RETRIES: string;
    static SCENE_ONE_RETRY: string;
    static SCENE_N_RETRIES_SUFFIX: string;
    static SCENE_ADVANCED_PROPERTIES: string;
    static SCENE_DEVICE_COMMUNICATION_PROP: string;
    static PLM_COMMUNICATIONS_MENU: string;
    static PLM_COMMUNICATIONS_TITLE: string;
    static PLM_COMMUNICATIONS_DESC: string;
    static FANLINC_OFF: string;
    static FANLINC_LOW: string;
    static FANLINC_MED: string;
    static FANLINC_HIGH: string;
    static EZFLORA_ZONE_8_PUMP: string;
    static EZFLORA_ZONE_8_NORMAL: string;
    static RL2_LED_LABEL: string;
    static RL2_BEEP_LABEL: string;
    static RL2_4_BUTTON_LABEL: string;
    static RL2_8_BUTTON_NON_TOG_LABEL: string;
    static RL2_8_BUTTON_TOG_LABEL: string;
    static RL2_1_BUTTON_LABEL: string;
    static RL2_2_BUTTON_NON_TOG_LABEL: string;
    static RL2_2_BUTTON_TOG_LABEL: string;
    static RL2_CHANGE_BUTTON_CONFIG_TITLE: string;
    static CLIMATE_INCREMENT_SETPOINT: string;
    static CLIMATE_DECREMENT_SETPOINT: string;
    static MASTER_CONTROLLER_LABEL: string;
    static SLAVE_LABEL: string;
    static SCENE_ATTRIBUTES: string;
    static COPYING_SCENE_ATTRIBUTES: string;
    static GLOBALLY_CHANGE_SCENE_ATTRIBUTES: string;
    static NODE_LABEL: string;
    static A10_NODE_LABEL: string;
    static LINK_SENSOR_LABEL: string;
    static LINK_HIDDEN_DOOR_SENSOR_LABEL: string;
    static LINK_OPEN_CLOSE_SENSOR_LABEL: string;
    static LINK_LEAK_SENSOR_LABEL: string;
    static LINK_MOTION_SENSOR_LABEL: string;
    static LINK_MOTION_SENSOR_II_LABEL: string;
    static LINK_REMOTELINC2_LABEL: string;
    static LINK_REMOTELINC2_SWITCH_SUBLABEL: string;
    static LINK_REMOTELINC2_4SCENE_SUBLABEL: string;
    static LINK_REMOTELINC2_8SCENE_SUBLABEL: string;
    static LINK_CONTROLINC_LABEL: string;
    static LINK_REMOTELINC_LABEL: string;
    static LINK_IRLINC_RX_LABEL: string;
    static LINK_IRLINC_TX_LABEL: string;
    static LINK_EZSNSRF_LABEL: string;
    static LINK_EZX10RF_LABEL: string;
    static KEYPADLINC: string;
    static BUTTONS_GROUPING: string;
    static MUTUALLY_EXCLUSIVE_BUTTONS: string;
    static BUTTON_TOGGLE: string;
    static BUTTON_BACKLIGHT: string;
    static THERMOSTAT_HUMIDTY: string;
    static PLM: string;
    static TOGGLE_CONTROLLER_RESPONDER: string;
    static TOGGLE_BUTTON_TOGGLE: string;
    static SET_TOGGLE_MODE: string;
    static TOGGLE_MODES: string;
    static ALL_TOGGLE_LABEL: string;
    static ALL_NON_TOGGLE_LABEL: string;
    static SET_SCHEDULE: string;
    static SET_OPTIONS: string;
    static LOCAL_ONLY_LABEL: string;
    static AUTO_DISCOVER_LABEL: string;
    static CHOOSE_BRIDGE_TYPE: string;
    static GET_PLM_STATUS: string;
    static SHOW_PLM_LINKS: string;
    static SHOW_DEVICE_LINKS: string;
    static SHOW_ISY_LINKS: string;
    static PLM_LINKS_TABLE: string;
    static DEVICE_LINKS_TABLE: string;
    static ADVANCED_OPTIONS: string;
    static SCENE_TEST: string;
    static ADVANCED_OPTIONS_ENGINE: string;
    static USE_I1_ONLY: string;
    static CALBIRATE_ENGINE_VERSIONS: string;
    static DEVICE_REPORTED_VERSION: string;
    static ISY_LINK_TABLE: string;
    static DL_FROM_LINK: string;
    static DL_READ: string;
    static DL_LINKS: string;
    static START_LINK_ADDRESS: string;
    static END_LINK_ADDRESS: string;
    static SENSITIVITY_LEVEL: string;
    static SENSING_MODE: string;
    static NIGHT_ONLY_MODE: string;
    static ON_ONLY_MODE: string;
    static NIGHT_ONLY_MODE_CHECKED: string;
    static ON_ONLY_MODE_CHECKED: string;
    static PROGRAM_LOCK: string;
    static LED_ON_TX: string;
    static RELAY_FOLLOWS_INPUT: string;
    static MOMENTARY_A: string;
    static LATCH: string;
    static MOMENTARY_BOTH: string;
    static MOMENTARY_LOOK_AT_SENSOR: string;
    static SEND_X10: string;
    static TRIGGER_OFF: string;
    static BEEP: string;
    static TIMER_ENABLED: string;
    static TRIGGER_GROUP_ON: string;
    static LED_ON: string;
    static ONE_MIN_LOCAL_WARNING: string;
    static DEFAULT_TIMEOUT_VALUE: string;
    static TRIGGER_THRESHOLD_WATTS: string;
    static HOLD_OFF_SECS: string;
    static HYSTERESIS_WATTS: string;
    static MICRO_OPEN_CLOSE_MOMENTARY_TIMEOUT: string;
    static getDeviceDetails(family: number, typeCode: string): {
        name: string;
        modelNumber: string;
        version: string;
        class: typeof ISYDevice;
    };
    static getInsteonDeviceDetails(typeCode: string): {
        name: string;
        modelNumber: string;
        version: string;
        class: typeof ISYDevice;
    };
    static getNLSNetworkBridgeInfo(device: number): any;
    static getNLSIrrigationControlInfo(device: number): string;
    static getNLSSwitchLightInfo(device: number): {
        name: string;
        modelNumber: string;
        version: string;
        class: typeof ISYDevice;
    };
    private static getNLSDimLightInfo;
    private static getNLSControllerInfo;
    private static getNLSIOControlInfo;
    private static getNLSSHS;
    private static getNLSClimateControlInfo;
    private static getNLSAccessControlInfo;
    private static getNLSEnergyManagement;
    private static getNLSWindowsCovering;
}
