/// <reference types="node" />
declare const InsteonKeypadDimmerDevice_base: {
    new (isy: any, node: any): {
        [x: string]: any;
        addChild(childDevice: import("../ISYDevice").ISYDevice<import("../../Families").Family.Insteon>): void;
        convertFrom(value: any, uom: number): any;
        convertTo(value: any, uom: number): any;
        sendBeep(level?: number): Promise<any>;
        family: import("../../Families").Family.Insteon;
        readonly typeCode: string;
        readonly deviceClass: any;
        readonly parentAddress: any;
        readonly category: number;
        readonly subCategory: number;
        readonly type: any;
        _parentDevice: import("../ISYDevice").ISYDevice<import("../../Families").Family.Insteon>;
        readonly children: import("../ISYDevice").ISYDevice<import("../../Families").Family.Insteon>[];
        readonly scenes: import("../../ISYScene").ISYScene[];
        readonly formatted: any;
        readonly uom: any;
        readonly pending: any;
        hidden: boolean;
        location: string;
        addLink(isyScene: import("../../ISYScene").ISYScene): void;
        readonly parentDevice: import("../ISYDevice").ISYDevice<import("../../Families").Family.Insteon>;
        refreshProperty(propertyName: string): Promise<any>;
        refreshNotes(): Promise<void>;
        getNotes(): Promise<any>;
        updateProperty(propertyName: string, value: string): Promise<any>;
        sendCommand(command: any, ...parameters: any[]): Promise<any>;
        refresh(): Promise<any>;
        handlePropertyChange(propertyName: string, value: any, formattedValue: string): boolean;
        readonly isy: import("../../ISY").ISY;
        readonly flag: any;
        readonly nodeDefId: string;
        readonly address: string;
        name: string;
        displayName: string;
        folder: string;
        parent: any;
        parentType: import("../../ISYConstants").NodeType;
        readonly elkId: string;
        nodeType: number;
        propertyChanged: import("events").EventEmitter;
        propsInitialized: boolean;
        logger: (msg: any) => void;
        lastChanged: Date;
        enabled: boolean;
        handleEvent(event: any): boolean;
        onPropertyChanged(propertyName: any, callback: (...args: any[]) => void): void;
    };
};
export declare class InsteonKeypadDimmerDevice extends InsteonKeypadDimmerDevice_base {
    constructor(isy: any, deviceNode: any);
}
declare const InsteonKeypadRelayDevice_base: {
    new (isy: any, node: any): {
        [x: string]: any;
        addChild(childDevice: import("../ISYDevice").ISYDevice<import("../../Families").Family.Insteon>): void;
        convertFrom(value: any, uom: number): any;
        convertTo(value: any, uom: number): any;
        sendBeep(level?: number): Promise<any>;
        family: import("../../Families").Family.Insteon;
        readonly typeCode: string;
        readonly deviceClass: any;
        readonly parentAddress: any;
        readonly category: number;
        readonly subCategory: number;
        readonly type: any;
        _parentDevice: import("../ISYDevice").ISYDevice<import("../../Families").Family.Insteon>;
        readonly children: import("../ISYDevice").ISYDevice<import("../../Families").Family.Insteon>[];
        readonly scenes: import("../../ISYScene").ISYScene[];
        readonly formatted: any;
        readonly uom: any;
        readonly pending: any;
        hidden: boolean;
        location: string;
        addLink(isyScene: import("../../ISYScene").ISYScene): void;
        readonly parentDevice: import("../ISYDevice").ISYDevice<import("../../Families").Family.Insteon>;
        refreshProperty(propertyName: string): Promise<any>;
        refreshNotes(): Promise<void>;
        getNotes(): Promise<any>;
        updateProperty(propertyName: string, value: string): Promise<any>;
        sendCommand(command: any, ...parameters: any[]): Promise<any>;
        refresh(): Promise<any>;
        handlePropertyChange(propertyName: string, value: any, formattedValue: string): boolean;
        readonly isy: import("../../ISY").ISY;
        readonly flag: any;
        readonly nodeDefId: string;
        readonly address: string;
        name: string;
        displayName: string;
        folder: string;
        parent: any;
        parentType: import("../../ISYConstants").NodeType;
        readonly elkId: string;
        nodeType: number;
        propertyChanged: import("events").EventEmitter;
        propsInitialized: boolean;
        logger: (msg: any) => void;
        lastChanged: Date;
        enabled: boolean;
        handleEvent(event: any): boolean;
        onPropertyChanged(propertyName: any, callback: (...args: any[]) => void): void;
    };
};
export declare class InsteonKeypadRelayDevice extends InsteonKeypadRelayDevice_base {
    constructor(isy: any, deviceNode: any);
}
export {};
